// Generated by ts-to-zod
import { z } from "zod";

export const postSchema = z.object({
  publish_date: z.number().nullable(),
  update_date: z.number().optional().nullable(),
  title: z.string(),
  slug: z.string(),
  summary: z.string(),
  content: z.string().nullable(),
  image: z.string().optional().nullable(),
  tags: z.array(z.string()),
  authors: z.array(z.string()),
});

export const postPreviewSchema = postSchema.pick({
  title: true,
  tags: true,
  slug: true,
  summary: true,
  publish_date: true,
});
